import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/client/react-query/react-query";
import { Toaster } from "@/components/ui/toaster";

import { Figtree } from "next/font/google";

export const metadata: Metadata = {
  title: "ADTO Client Side Landing",
  description: "Generated by create next app",
};

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" className="scroll-smooth">
        <body className={`antialiased ${figtree.className}`}>
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
