import NavigationBar from "@/components/ui/NavigationBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  icons: {
    icon: "/images/ADTO2_Blue.svg",
  },
  title: "ADTO Client Side",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`antialiased`}>
      <main>
        <NavigationBar />
        {children}
      </main>
    </div>
  );
}
